OpenVPN Password-less Login
===========================
William Blankenship <william.jblankenship@gmail.com>
v1.0, April 2017: Documenting Nord process
:nord: https://nordvpn.com

== Updating config files

Lets say you were given a set of vpn configuration files (from a company like
{nord}[nordvpn]), and these config files prompt for your user-name and password
at every login.

Open up any one of these files, and somewhere you should see the line:

-------------------------------------------------------------------------------
auth-user-pass
-------------------------------------------------------------------------------

This is indicating to OpenVPN that you would like to use a username and
password to login to the service. This command accepts an optional second
parameter, which is a path to a file containing the plain-text credentials for
logging into your vpn.

Within the directory containing your VPN config files, run the following
commands:

-------------------------------------------------------------------------------
$ sed -i 's/auth-user-pass/auth-user-pass password.txt/g' *
$ echo 'username@foo.bar' > password.txt
$ # Note, the following line will be recorded in your .bashrc, it would be best
$ # if instead you opened password.txt in a text editor and typed your password
$ echo 'plaintextpassword' >> password.txt
$ # Make sure only your user (and root) can read password.txt
$ chmod 600 password.txt
-------------------------------------------------------------------------------

[NOTE]
===============================================================================

If you run openvpn using the root user, which is usually required, and the
above commands were run under your normal user, `chmod 600 password.txt` will
prevent the root user from being able to login. You need to transfer ownership
of `password.txt` to `root`. Execute:

-------------------------------------------------------------------------------
sudo chown root:root password.txt
-------------------------------------------------------------------------------

===============================================================================

Now when you use OpenVPN to connect, you will no longer be prompted for a
password.
