Syntax Highlighting in Vim
==========================
William Blankenship <william.jblankenship@gmail.com>
v1.1, April 2017: pat -> pattern
:autocmd: http://vimdoc.sourceforge.net/htmldoc/autocmd.html


== Syntax Highlighting

Syntax files are generally placed in the +./syntax+ subdirectory of your vim
plugin. They declare a set of highlighting rules for a language. I don't know
how to make them.

The language name is exported using the +let b:current_syntax=[LANGUAGE]+,
+[LANGUGE]+ can then be used to refer to the highlighting rules defined in
that file.

== Extension Matching

The logic for matching a file extension to a language is generally placed in
the +./ftdetect+ folder of your vim plugin. Here we take advantage of the
{autocmd}[autocmd] function which, as the name implies, automates the execution
of a command.

The command we are going to automate is +setfiletype+, if you already have a
language file installed for your language under +./syntax+ as described above,
you can test out this command using +:setf [LANGUAGE]+ from command mode
(+setf+ is short for +setfiletype+).

The command +autocmd+ works by defining a set of events to run a command in
response to, and then narrowing the files that the command should be run
against using a matching pattern. This looks like +autocmd {event} {pattern}
cmd+. We are interested in running our +setf+ command every time a file loads,
which happens when we open a file or create a file: +BufRead,BufNewFile+. Lets
say we are trying to match +asciidoc+ files, we would want to match all files
with an extension of +.adoc+: +*.adoc+.

Putting this all together, we get:

+./ftdetect/asciidoc.vim+
--------------------------------------
autocmd BufRead,BufNewFile *.adoc setf asciidoc
--------------------------------------
